export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  promotions: "/promotions",
  offer: "/offer/events",
  promote: "/promote",
  claim: "/claim",
  dailySpin: "/daily-spin",
  spinRally: "/spin-ralley",
  tournament: "/tournament",
  games: "/games",
  favorites: "/favorites",
  providers: "/providers",
  gamesCategory: "/games-category",
  sports: "/sports",
  profile: "/profile",
  profileData: "/profile/data",
  profileSecurity: "/profile/security",
  wallet: "/wallet",
  report: "/home/report",
  vip: "/vip",
  vipLevel: "/vip-level",
  download: "/download",
  referral: "/referral",
  affiliate: "/affiliate",
  support: "/support",
} as const;
