export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  promotions: "/promotions",
  dailySpin: "/daily-spin",
  spinRally: "/spin-ralley",
  tournament: "/tournament",
  games: "/games",
  favorites: "/favorites",
  providers: "/providers",
  gamesCategory: "/games-category",
  sports: "/sports",
  profile: "/profile",
  wallet: "/wallet",
  vip: "/vip",
  vipLevel: "/vip-level",
  download: "/download",
  referral: "/referral",
  affiliate: "/affiliate",
  support: "/support",
} as const;
